In [ ]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go


In [ ]:
!wget https://github.com/plotly/orca/releases/download/v1.2.1/orca-1.2.1-x86_64.AppImage -O /usr/local/bin/orca
!chmod +x /usr/local/bin/orca
!apt-get install xvfb libgtk2.0-0 libgconf-2-4

--2023-10-24 19:05:03--  https://github.com/plotly/orca/releases/download/v1.2.1/orca-1.2.1-x86_64.AppImage
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/99037241/9dc3a580-286a-11e9-8a21-4312b7c8a512?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231024%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231024T190504Z&X-Amz-Expires=300&X-Amz-Signature=3e51d5d9dbf6dc188f1a887cf3b6c0775685e07ccdcd2c4522e38b168eb2706c&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=99037241&response-content-disposition=attachment%3B%20filename%3Dorca-1.2.1-x86_64.AppImage&response-content-type=application%2Foctet-stream [following]
--2023-10-24 19:05:04--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/99037241/9dc3a580-286a-11e9-8a21-4312b7c

In [ ]:
!wget "https://archive.org/download/ages-and-heights/AgesAndHeights.pkl"

--2023-10-24 19:05:45--  https://archive.org/download/ages-and-heights/AgesAndHeights.pkl
Resolving archive.org (archive.org)... 207.241.224.2
Connecting to archive.org (archive.org)|207.241.224.2|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ia801802.us.archive.org/31/items/ages-and-heights/AgesAndHeights.pkl [following]
--2023-10-24 19:05:45--  https://ia801802.us.archive.org/31/items/ages-and-heights/AgesAndHeights.pkl
Resolving ia801802.us.archive.org (ia801802.us.archive.org)... 207.241.230.172
Connecting to ia801802.us.archive.org (ia801802.us.archive.org)|207.241.230.172|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2406 (2.3K) [application/octet-stream]
Saving to: ‘AgesAndHeights.pkl’

AgesAndHeights.pkl  100%[===================>]   2.35K  --.-KB/s    in 0s      

2023-10-24 19:05:46 (565 MB/s) - ‘AgesAndHeights.pkl’ saved [2406/2406]



In [ ]:
data=pd.read_pickle('AgesAndHeights.pkl')
data

Age     Height
0   14.767874  59.627484
1    3.107671  36.146453
2    7.266917  46.912878
3    1.815180  29.125660
4   16.753758  68.170414
..        ...        ...
95   7.323712  46.857505
96   5.591509  39.339990
97   2.625606  32.918925
98   5.519293  40.704154
99  13.117413  55.177407

[100 rows x 2 columns]

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(data, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(data, *['Height'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plot(df, x_colname, y_colname, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(6 * figscale, 6 * figscale))
  df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha)
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plot(data, *['Age', 'Height'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(data, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(data, *['Height'], **{})
chart

In [ ]:
ages = data['Age']
heights = data['Height']

fig = px.scatter(x=ages, y=heights, title="Height vs Age", labels={'x': 'Age (Years)',
                                                                   'y': 'Height (Inches)'})
fig.show()

In [ ]:
ages[ages<0]

13   -0.163532
20   -0.683017
25   -0.146392
30   -0.780853
36   -0.087958
59   -0.548488
91   -0.328780
Name: Age, dtype: float64

In [ ]:
x = ages.to_numpy()
y = heights.to_numpy()
x

array([14.76787382,  3.10767135,  7.26691701,  1.81517968, 16.75375763,
        5.35126307,  8.65571488,  4.20599293,  7.35669106,  1.66817819,
        8.2969588 , 14.74948482, 15.28545214, -0.16353169, 16.65534197,
        0.85918789,  8.43332999, 11.92386163,  0.76828323, 11.36202254,
       -0.68301696,  1.29597926, 10.31206094, 17.39335272, 10.31003056,
       -0.14639168,  6.23764582, 15.55153122,  2.77346425, 15.59798962,
       -0.78085287,  7.57789784,  2.04165705,  9.90665221,  2.87252515,
        1.54231936, -0.08795844,  5.46202264, 15.04362695,  5.99372597,
        4.805291  ,  8.94992003,  5.02020985,  9.89555258,  5.20281507,
        0.19568558,  0.89217393,  7.30979593, 10.8545723 , 15.69876495,
        0.81216582, 15.40144747,  9.21599924,  8.98515379,  3.74369906,
        0.75192511,  6.5963469 ,  9.75112683,  7.40094567, -0.5484884 ,
       17.32712575, 10.53406938, 15.16816596,  9.46971876, 13.54691548,
        7.80132294,  2.51910344,  4.71666526, 10.0386595 , 11.77

In [ ]:
model = LinearRegression().fit(x.reshape((len(x), 1)), heights)
model.coef_

array([1.9855967])

In [ ]:
x_new = np.arange(18).reshape((18, 1))
preds  = model.predict(x_new)

fig = px.scatter(x=ages, y=heights, title="Height vs Age", labels={'x': 'Age (Years)',
                                                                   'y': 'Height (Inches)'})
fig.add_trace(
    go.Scatter(x=x_new.reshape(x_new.shape[0]), y=preds, mode='lines', name='Model'))

fig.show()

In [ ]:
from joblib import dump, load
dump(model, 'model.joblib')

['model.joblib']

In [ ]:
loaded_model = load('model.joblib')

In [ ]:
more_preds  = loaded_model.predict(x_new)
more_preds

array([30.13813668, 32.12373339, 34.10933009, 36.0949268 , 38.0805235 ,
       40.06612021, 42.05171691, 44.03731361, 46.02291032, 48.00850702,
       49.99410373, 51.97970043, 53.96529714, 55.95089384, 57.93649055,
       59.92208725, 61.90768396, 63.89328066])

In [ ]:
def make_picture(training_data_filename, new_input_arr, model, output_file='predictions_pic.svg'):
  # Plot training data with model
  data = pd.read_pickle('AgesAndHeights.pkl')
  x_new = np.arange(18).reshape((18, 1))
  preds  = model.predict(x_new)
  ages = data['Age']
  heights = data['Height']
  fig = px.scatter(x=ages, y=heights, title="Height vs Age", labels={'x': 'Age (Years)',
                                                                   'y': 'Height (Inches)'})
  fig.add_trace(
      go.Scatter(x=x_new.reshape(x_new.shape[0]), y=preds, mode='lines', name='Model'))

  if new_input_arr is not False:
    # Plot new predictions
    new_preds = model.predict(new_input_arr)
    fig.add_trace(
      go.Scatter(x=new_input_arr.reshape(new_input_arr.shape[0]), y=new_preds, name='New Outputs', mode='markers', marker=dict(
            color='purple',
            size=20,
            line=dict(
                color='purple',
                width=2
            ))))
  fig.write_image(output_file, width=800)
  return fig

In [ ]:
def floats_string_to_input_arr(floats_str):
  floats = [float(x.strip()) for x in floats_str.split(',')]
  as_np_arr = np.array(floats).reshape(len(floats), 1)
  return as_np_arr

In [ ]:
make_picture('AgesAndHeights.pkl', False, loaded_model, 'base_pic.svg')